### ISSUE TITLE
Homebridge crashes after new update when adding TV

### ISSUE THREAD

**Issue by lc808** [normen/homebridge-bravia#130]
Hi,

I just updated to the v2.4.6. Everything fine so far, the TV is shown in homebridge, but when I try to add it in Homekit (add Device) the adding window in homekit says connecting, seems to freeze, because the homebrigde is crashing.

After restarting the homebridge the TV also don`t appear anymore as device to be added, so i have to change the name in the config and pair it again.

This is the log:

Service Bravia TV 66FD._hap._tcp.local.
    at Responder.handleServiceRecordUpdate (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/Responder.ts:410:13)
    at CiaoService.emit (events.js:315:20)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/CiaoService.ts:461:14)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[9/22/2020, 6:50:21 PM] Got SIGTERM, shutting down Homebridge...
[9/22/2020, 6:50:22 PM] ERR_SERVER_CLOSED: Cannot send packets on a closed mdns server!
    at MDNSServer.assertBeforeSend (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:354:13)
    at MDNSServer.sendOnAllNetworks (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:274:10)
    at MDNSServer.sendQueryBroadcast (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:235:26)
    at Prober.sendProbeRequest (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/responder/Prober.ts:155:17)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by lc808** [comment]
I found the issue: i had the TV several times already in cache (due to all the testing after ios14 update), after clearing it runs smooth.
