### ISSUE TITLE
Device no response

### ISSUE THREAD

**Issue by sadden3194** [normen/homebridge-bravia#160]
Hi,

all works fine a few minutes ago. I could turn off / on the tv.
But now I get no response.

Log:
[9/10/2021, 3:43:54 PM] [BraviaPlatform] Initializing BraviaPlatform platform...
[9/10/2021, 3:43:54 PM] [BraviaPlatform] Cached external accessory Fehrnsehr Wohnzimmer found and restored
[9/10/2021, 3:43:54 PM] [BraviaPlatform] Added input HDMI 1
[9/10/2021, 3:43:54 PM] [BraviaPlatform] Added input HDMI 2/MHL
[9/10/2021, 3:43:54 PM] [BraviaPlatform] Added input HDMI 3
[9/10/2021, 3:43:54 PM] [BraviaPlatform] Added input HDMI 4
[9/10/2021, 3:43:54 PM] [BraviaPlatform] Added input AV1
[9/10/2021, 3:43:54 PM] [BraviaPlatform] Added input Player 1
[9/10/2021, 3:43:54 PM] [BraviaPlatform] Added input Player 2
[9/10/2021, 3:43:54 PM] [BraviaPlatform] Added input Bildschirm spiegeln
[9/10/2021, 3:43:57 PM] [BraviaPlatform] Error:  Error: connect EHOSTUNREACH 192.168.108.29:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.108.29',
  port: 80
}

**Comment by normen** [comment]
Yeah, seems like you can't get a network connection. Thats no problem of this plugin though. Maybe the TVs IP changed or something, make sure you set a fixed IP (or a hostname) in your router.

**Comment by sadden3194** [comment]
<img width="459" alt="Bildschirmfoto 2021-09-11 um 12 18 47" src="https://user-images.githubusercontent.com/17011498/132944626-94570803-3c16-48d8-a5f3-b7a50b58108e.png">

No, IP is correctly

**Comment by normen** [comment]
> [9/10/2021, 3:43:57 PM] [BraviaPlatform] Error: Error: connect EHOSTUNREACH 192.168.108.29:80
> at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
> errno: -113,
> code: **'EHOSTUNREACH',**
> syscall: 'connect',
> address: '192.168.108.29',
> port: 80
> }

Still your homebridge computer clearly can't connect to the TV.

**Comment by sadden3194** [comment]
I added the mac address now and at the moment it looks like okay again.

**Comment by normen** [comment]
That just enables Wake-On-Lan, which switches on the TV with a hardware event instead of using the AndroidTV web API. If that fixes it, you probably didn't enable "remote start" in your TV as the README says and consequently it just doesn't respond to network API requests when it's in deep sleep.

**Comment by sadden3194** [comment]
the "problem" is that I have no android tv. it is a simple one

**Comment by normen** [comment]
The used web api is Sony specific, not AndroidTV specific. If you can do more than turn on/off the TV (i.e. change channels and volume) then the TV supports the web API. Actually the fact that you could turn it on without WOL hints at that too.

**Comment by sadden3194** [comment]
okay I understood. I need only the function "turn on / off". I guess that If I restart the homebridge while the tv is on: it will works. But If the tv is a time off, I get no response anymore. I will watch it
