### ISSUE TITLE
Homebridge quit with error from the bravia plugin

### ISSUE THREAD

**Issue by rambits** [normen/homebridge-bravia#28]
The homebridge crushed when I sent a "turn off my TV command", log as follow:

[2018-3-17 00:14:54] [BraviaPlatform] Wild TV (kamaji://OPA-WILD-TV)
[2018-3-17 00:14:54] [BraviaPlatform] WIMZTV (kamaji://OPA-WIMZTV)
[2018-3-17 00:14:54] [BraviaPlatform] Winter Olympic Games Quiz (kamaji://OPA-WINTER-OLYMPIC-GAMES-QUIZ)
[2018-3-17 00:14:54] [BraviaPlatform] Learn Chinese with David (kamaji://OPA-LEARN-CHINESE-WITH-DAVID)
[2018-3-17 00:14:54] [BraviaPlatform] Sportfishing with Dan Hernandez (kamaji://OPA-SPORTFISHING-WITH-DAN-HERNANDEZ)
[2018-3-17 00:14:54] [BraviaPlatform] The Cocktail Spirit with Robert Hess (kamaji://OPA-THE-COCKTAIL-SPIRIT-WITH-ROBERT-HESS)
[2018-3-17 00:14:54] [BraviaPlatform] Raising the Bar with Jamie Boudreau (kamaji://OPA-RAISING-THE-BAR-WITH-JAMIE-BOUDREAU)
[2018-3-17 00:14:54] [BraviaPlatform] Little Big World (kamaji://OPA-LITTLE-BIG-WORLD)
[2018-3-17 00:14:54] [BraviaPlatform] World Clocks (kamaji://OPA-WORLD-CLOCKS)
[2018-3-17 00:14:54] [BraviaPlatform] World Snowboard Tour (kamaji://OPA-WORLD-SNOWBOARD-TOUR-2)
[2018-3-17 00:14:54] [BraviaPlatform] The World Today with Tariq Ali (kamaji://OPA-THE-WORLD-TODAY-WITH-TARIQ-ALI)
[2018-3-17 00:14:54] [BraviaPlatform] Freeride World Tour TV (kamaji://OPA-FREERIDE-WORLD-TOUR-TV)
[2018-3-17 00:14:54] [BraviaPlatform] WOWTV (kamaji://OPA-WOWTV)
[2018-3-17 00:14:54] [BraviaPlatform] WOWtv.com (kamaji://OPA-WOWTVCOM)
[2018-3-17 00:14:54] [BraviaPlatform] Xtreme Films (kamaji://OPA-XTREME-FILMS)
[2018-3-17 00:14:54] [BraviaPlatform] I Me & Yoga (kamaji://OPA-I-ME-YOGA)
[2018-3-17 00:14:54] [BraviaPlatform] kAca yoga (kamaji://OPA-KACA-YOGA)
[2018-3-17 00:14:54] [BraviaPlatform] Young Hollywood (kamaji://OPA-YOUNG-HOLLYWOOD)
[2018-3-17 00:14:54] [BraviaPlatform] Colour In Your Life (kamaji://OPA-COLOUR-IN-YOUR-LIFE)
[2018-3-17 00:14:54] [BraviaPlatform] SKUFF YOUTH LIFESTYLE CHANNEL - LIVE (kamaji://OPA-SKUFF-YOUTH-LIFESTYLE-CHANNEL-LIVE)
[2018-3-17 00:14:54] [BraviaPlatform] YuppTV (kamaji://OPA-YUPPTV-2)
[2018-3-17 00:14:54] [BraviaPlatform] Não é Sério (kamaji://OPA-NAO-E-SERIO)
[2018-3-17 00:14:54] [BraviaPlatform] Ñ Don't Stop (kamaji://OPA-N-DONT-STOP)
[2018-3-17 00:14:54] [BraviaPlatform] Восьмой канал (kamaji://OPA-VOSMOI-KAANAL)
[2018-3-17 00:14:54] [BraviaPlatform] Internet Browser (preset://web-browser)
[2018-3-17 00:14:54] [BraviaPlatform] Photo Share (preset://photoshare)
[2018-3-17 00:14:54] [BraviaPlatform] Screen mirroring (preset://wifi-display)
[2018-3-17 00:14:54] [BraviaPlatform] Home Theater Control (preset://home-theater-control)
[2018-3-17 00:14:54] [BraviaPlatform] "α" CLOCK (aapp://aais-app://com.sony.braviaaclock/com.sony.braviaaclock.MainActivity)
[2018-3-17 00:14:54] [BraviaPlatform] Media Player (aapp://aais-app://com.sony.dtv.mediaplayer/com.sony.dtv.mediaplayer.MediaContentsBrowserActivity)
[2018-3-17 00:14:54] [BraviaPlatform] Photo Frame Mode (aapp://aais-app://com.sony.braviaphotoframemode/com.sony.photoframe.PhotoFrameAppActivity)
/usr/lib/node_modules/homebridge-bravia/index.js:307
    callback(null, 0);
    ^

ReferenceError: callback is not defined
    at onError (/usr/lib/node_modules/homebridge-bravia/index.js:307:5)
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-bravia/index.js:225:9)
    at ClientRequest.emit (events.js:180:13)
    at Socket.socketErrorListener (_http_client.js:394:9)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)

**Comment by normen** [comment]
Thanks, fixed in 0.9.6
