### ISSUE TITLE
Homebridge suddenly stop with this error message . how can i do?

### ISSUE THREAD

**Issue by bmbking56** [normen/homebridge-bravia#30]
Works well but sometimes
homebridge suddenly stop with this error message. how can i do?

=====================================
/usr/local/lib/node_modules/homebridge-bravia/index.js:303
            var reslt = jayons.result[0];
                                     ^

TypeError: Cannot read property '0' of undefined
    at onSucces (/usr/local/lib/node_modules/homebridge-bravia/index.js:303:38)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-bravia/index.js:215:17)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)

==============================

This issue tracker is ONLY for BUG REPORTS with proper error descriptions, instructions for recreating the bug, message logs and hard- and software descriptions.

Please understand that this is NOT a support forum, there IS NO SUPPORT for this free software outside of the manual. Requests for help or support WILL be closed without answer.

**Comment by normen** [comment]
Apparently your TV doesn't support listing it's applications.
