### ISSUE TITLE
TypeError: Cannot read property 'appsEnabled'

### ISSUE THREAD

**Issue by gielk** [normen/homebridge-bravia#39]
TypeError: Cannot read property 'appsEnabled' of undefined
    at BraviaTV.configureAccessory (/usr/local/lib/node_modules/homebridge-bravia-tv/src/platform.js:567:21)
    at Server._configCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:386:24)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:93:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by normen** [comment]
Dude - wrong plugin
