### ISSUE TITLE
Homebrdige crashes after installing plugin

### ISSUE THREAD

**Issue by MasterofKungfu9999** [normen/homebridge-bravia#68]
Hi,
im using hoobs and after installing the plugin, homebridge crashes.

Here is the log:

[Homebridge] [5/1/2020, 21:09:08] [BraviaPlatform] Initializing BraviaPlatform platform...
[Homebridge] [5/1/2020, 21:09:08] TypeError: Cannot read property 'forEach' of undefined
    at BraviaPlatform.accessories (/home/hoobs/.hoobs/node_modules/homebridge-bravia/index.js:24:19)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/server.js:373:22)
    at Server._loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/server.js:302:18)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/server.js:93:14)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/cli.js:74:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/bin/homebridge:27:59)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
[Homebridge] [5/1/2020, 21:09:08] Got SIGTERM, shutting down Homebridge...

**Comment by normen** [comment]
This is fixed in v2.0
