### ISSUE TITLE
Exception!  TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by t-wei** [normen/homebridge-bravia#75]
I get many exceptions recently:
[5/5/2020, 9:08:40 PM] [BraviaPlatform] Exception!  TypeError: Cannot read property '0' of undefined
    at onSucces (/homebridge/node_modules/homebridge-bravia/index.js:464:36)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-bravia/index.js:836:9)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

---

I configured homebridge with:
{
            "tvs": [
                {
                    "name": "Fernseher",
                    "ip": "tv266fd9b27e8c",
                    "mac": "54:35:30:78:89:e9",
                    "cookiepath": "/homebridge/cookiefile",
                    "pwd": "XXXX",
                    "soundoutput": "speaker",
                    "tvsource": "tv:dvbc"
                }
            ],
            "platform": "BraviaPlatform"
        }

---

I have homebridge runing in the docker-container (version 1.0.4, Node.js Version v12.14.0, Npm Version v6.13.4)

**Comment by normen** [comment]
It's just logging that it couldn't read the "play content" of the TV, i.e. the channel or input. Nothing to worry about, I'll make the message less obtrusive in a future update.
